# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QA-LlqHBDA3Bbi9EnouHKtpmEpgIz44J
"""

import streamlit as st
import pandas as pd

st.title("Workload Management - Sheet 1 (Data Worker)")

# Upload Excel
uploaded_file = st.file_uploader("Upload file Excel data worker", type=["xlsx"])

if uploaded_file:
    # Baca sheet pertama
    df = pd.read_excel(uploaded_file, sheet_name=0)

    # Mapping JOB ke JOBCODE (kategori ringkas)
    job_mapping = {
        'DE': 'Data Entry',
        'CHECKER INB': 'Checker',
        'CHECKER OUT': 'Checker',
        'SC': 'CBT',
        'RD': 'Operator',
        'TT': 'Toptier',
        'PM': 'PM',
        'PICKER': 'Picker',
        'WHMAN OUTB': 'TKBM',
        'WHMAN': 'TKBM'
    }

    # Tambahkan kolom JOBCODE
    df['JOBCODE'] = df['JOB'].map(job_mapping).fillna("Unknown Job")

    st.subheader("Data Worker:")
    st.dataframe(df[['NAMA', 'JOB', 'JOBCODE']])